### ISSUE TITLE
API_KEY is being requested although it has been setup as per documentation

### ISSUE THREAD

**Issue by danazkari** [kolach/loopback-component-cloudinary#1]
Seems like for some reason, the config being set in the `datasources.json` file, is not being carried over all the way to the cloudinary dependency package.

I configured everything almost to the letter as it's on the README, but I'm getting this error

![image](https://cloud.githubusercontent.com/assets/349542/22525690/dab04b66-e88d-11e6-8095-bf294dd37e3c.png)

The error occurs when I try to hit the `/pictures/upload` endpoint.

Which is weird, since I can tell you for sure the data has been set in the datasources file.

FYI, I'm using a `datasources.development.js` file instead of the json file.

**Comment by danazkari** [comment]
@kolach for what is worth, I think I found the issue, seems to be located in `cloudinary-service.js` and it's in lines 18 through 20.

One issue is that it's trying to use the config variables as camelCased instead of snake_cased, and also, it's trying to look for them in the `options` object, but it should be `options.config` instead.

I'll make a PR if ur ok with it :)

**Comment by danazkari** [comment]
Nevermind... Just realized ur repo is a fork of the original project (or is it the other way around?) anyways.... this is not the project hosted in NPM. I followed your README to use the NPM one...

Alright, anyways.... have a good one :)

**Comment by kolach** [comment]
ok, never mind. It already works in production for awhile, so I was surprised that there are some errors. It's not a fork by the way.
